import Head from "next/head";
import { NextPage } from "next";

const ProfilePage: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{color:"black"}}>
        User Profile Page
      </main>
    </>
  );
};

export default ProfilePage;


