import Head from "next/head";
import { api } from "~/utils/api";
import { SignedIn } from "@clerk/nextjs";
import type { NextPage } from "next";
import { PageLayout } from "~/components/layout";
import { DataGrid, GridColDef } from "@mui/x-data-grid";

const columns: readonly GridColDef<(typeof rows)[number]>[] = [
  { field: "id", headerName: "ID", width: 90 },
  {
    field: "saleDay",
    headerName: "Parchase Date",
    width: 150,
  },
  {
    field: "productDesc",
    headerName: "Product Description",
    width: 150,
  },
  {
    field: "productType",
    headerName: "Type of Product",
    width: 110,
  },
  {
    field: "price",
    headerName: "Price",
    type: "number",
    width: 110,
  },
  {
    field: "sealerId",
    headerName: "Sealer",
    width: 110,
  },
];

const rows = [
  {
    id: "hbiub",
    saleDay: new Date("2024-12-18T11:51:32.431Z"),
    productDesc: "iubxiuobweoiuxb",
    price: 14,
    productType: "iubx",
    sealerId: "ygtcvyutv",
  },
  {
    id: "kbioubviob",
    saleDay: new Date("2024-11-18T11:51:32.431Z"),
    productDesc: "Cersei",
    price: 31,
    productType: "ibx",
    sealerId: "ygtyutv",
  },
];

const Tablas: NextPage = () => {
  const { data, isLoading } = api.sales.getAllSales.useQuery();

  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Tables</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageLayout>
        <SignedIn>
          <DataGrid
            rows={data}
            columns={columns}
            initialState={{
              pagination: {
                paginationModel: {
                  pageSize: 7,
                },
              },
            }}
            pageSizeOptions={[7]}
            checkboxSelection
            disableRowSelectionOnClick
            style={{ backgroundColor: "lightgray" }}
          />
          You are signed In
        </SignedIn>
      </PageLayout>
    </>
  );
};

export default Tablas;
